#!/bin/sh

CAR_KBD=/etc/udev/hwdb.d/61-carpalx.hwdb

if [ $# -ne 0 ]; then
    if [ -e $CAR_KBD ]; then
	echo "CAR"
    else
	echo "QWE"
    fi
    exit 0  
fi

if [ -e $CAR_KBD ]; then
    mv $CAR_KBD $CAR_KBD~
else
    mv $CAR_KBD~ $CAR_KBD
fi

udevadm hwdb --update
sleep 1
udevadm trigger --subsystem-match="input"
