#!/bin/sh

KIN_KBD=/etc/udev/hwdb.d/61-kinesis.hwdb

if [ -e $KIN_KBD ]; then
    mv $KIN_KBD $KIN_KBD~
else
    mv $KIN_KBD~ $KIN_KBD
fi

systemd-hwdb update
udevadm trigger --subsystem-match="input"
