#!/bin/sh

CAR_KBD=/etc/udev/hwdb.d/61-carpalx.hwdb

if [ -e $CAR_KBD ]; then
    mv $CAR_KBD $CAR_KBD~
else
    mv $CAR_KBD~ $CAR_KBD
fi

udevadm hwdb --update
udevadm trigger --subsystem-match="input"
